a = b = c = " Python 2023"
print("a == b", a == b)
print("b == c", b == c)
print("a type", type(a))
print("b type", type(b))
print("c type", type(c))
print("a address", hex(id(a)))
print("b address", hex(id(b)))
print("c address", hex(id(c)))
print("c = 'Java 11'")
c = "Java 11"
print("a == b", a == b)
print("b == c", b == c)
print("a type", type(a))
print("b type", type(b))
print("c type", type(c))
print("a address", hex(id(a)))
print("b address", hex(id(b)))
print("c address", hex(id(c)))
